# Etap 1: build Angulara
FROM node:20-alpine AS build

WORKDIR /app

# Skopiuj package.json i package-lock.json
COPY package*.json ./

# Zainstaluj zależności
RUN npm install

# Skopiuj resztę projektu
COPY . .

# Zbuduj aplikację produkcyjnie
RUN npm run build --prod

# Etap 2: serwowanie przez Nginx
FROM nginx:alpine

# Usuń domyślny plik konfiguracyjny
RUN rm /etc/nginx/conf.d/default.conf

# Skopiuj własny plik konfiguracyjny Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Skopiuj zbudowany kod Angulara z etapu build
COPY --from=build /app/dist/browser /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
